# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\20190829\Ui_Config.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(431, 317)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.spilt = QtWidgets.QLineEdit(Form)
        self.spilt.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spilt.setObjectName("spilt")
        self.gridLayout.addWidget(self.spilt, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.split_comboBox = QtWidgets.QComboBox(Form)
        self.split_comboBox.setObjectName("split_comboBox")
        self.gridLayout.addWidget(self.split_comboBox, 0, 1, 1, 1)
        self.custom_split = QtWidgets.QCheckBox(Form)
        self.custom_split.setObjectName("custom_split")
        self.gridLayout.addWidget(self.custom_split, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.t_comboBox = QtWidgets.QComboBox(Form)
        self.t_comboBox.setCurrentText("")
        self.t_comboBox.setObjectName("t_comboBox")
        self.gridLayout_2.addWidget(self.t_comboBox, 1, 1, 1, 1)
        self.t_unitcomboBox = QtWidgets.QComboBox(Form)
        self.t_unitcomboBox.setObjectName("t_unitcomboBox")
        self.t_unitcomboBox.addItem("")
        self.t_unitcomboBox.addItem("")
        self.gridLayout_2.addWidget(self.t_unitcomboBox, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.al_comboBox = QtWidgets.QComboBox(Form)
        self.al_comboBox.setObjectName("al_comboBox")
        self.gridLayout_2.addWidget(self.al_comboBox, 2, 1, 1, 1)
        self.al_unitcomboBox = QtWidgets.QComboBox(Form)
        self.al_unitcomboBox.setObjectName("al_unitcomboBox")
        self.al_unitcomboBox.addItem("")
        self.al_unitcomboBox.addItem("")
        self.gridLayout_2.addWidget(self.al_unitcomboBox, 2, 2, 1, 1)
        self.id_comboBox = QtWidgets.QComboBox(Form)
        self.id_comboBox.setObjectName("id_comboBox")
        self.gridLayout_2.addWidget(self.id_comboBox, 3, 1, 1, 1)
        self.id_unitcomboBox = QtWidgets.QComboBox(Form)
        self.id_unitcomboBox.setObjectName("id_unitcomboBox")
        self.id_unitcomboBox.addItem("")
        self.id_unitcomboBox.addItem("")
        self.id_unitcomboBox.addItem("")
        self.id_unitcomboBox.addItem("")
        self.id_unitcomboBox.addItem("")
        self.gridLayout_2.addWidget(self.id_unitcomboBox, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 0, 0, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.colorButton = QtWidgets.QPushButton(Form)
        self.colorButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.colorButton.setText("")
        self.colorButton.setObjectName("colorButton")
        self.gridLayout_3.addWidget(self.colorButton, 0, 1, 1, 1)
        self.color_comboBox = QtWidgets.QComboBox(Form)
        self.color_comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.color_comboBox.setObjectName("color_comboBox")
        self.gridLayout_3.addWidget(self.color_comboBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Form)
        self.al_comboBox.setCurrentIndex(-1)
        self.id_comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Config"))
        self.label_2.setText(_translate("Form", "Data Suorce Split TXT Config:"))
        self.label.setText(_translate("Form", "Split By:"))
        self.custom_split.setText(_translate("Form", "Use Custom"))
        self.label_3.setText(_translate("Form", "Data Suorce Column:"))
        self.label_5.setText(_translate("Form", "Unit"))
        self.label_4.setText(_translate("Form", "Time:"))
        self.t_unitcomboBox.setItemText(0, _translate("Form", "s"))
        self.t_unitcomboBox.setItemText(1, _translate("Form", "ms"))
        self.label_6.setText(_translate("Form", "Applied Load:"))
        self.label_7.setText(_translate("Form", "Column"))
        self.label_8.setText(_translate("Form", "Indentation Depth:"))
        self.al_unitcomboBox.setItemText(0, _translate("Form", "N"))
        self.al_unitcomboBox.setItemText(1, _translate("Form", "uN"))
        self.id_unitcomboBox.setItemText(0, _translate("Form", "m"))
        self.id_unitcomboBox.setItemText(1, _translate("Form", "cm"))
        self.id_unitcomboBox.setItemText(2, _translate("Form", "mm"))
        self.id_unitcomboBox.setItemText(3, _translate("Form", "um"))
        self.id_unitcomboBox.setItemText(4, _translate("Form", "nm"))
        self.label_10.setText(_translate("Form", "Color:"))
